FROM nginx:1.10.2

MAINTAINER Rob McLarty <r@robmclarty.com> (robmclarty.com)

EXPOSE 80 443

# Create directory for static files.
RUN mkdir -p /srv/opt/cred-auth-manager

# Remove default site.
RUN rm /etc/nginx/conf.d/default.conf

# Copy general nginx config.
COPY config/nginx/nginx.conf /etc/nginx/nginx.conf

# Process needs to run in foreground within container.
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

# Copy site-specific config.
COPY config/nginx/cred-auth-manager.conf /etc/nginx/conf.d/cred-auth-manager.conf

# Copy all static files to image.
COPY build /srv/opt/cred-auth-manager/

CMD ["nginx"]
